name: backend
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - name: run_tests
      run: yarn ci
    - name: push_coverage
      uses: codecov/codecov-action@v1
      if: always()
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        directory: